
branches:
  only:
  - master
  - develop
os: osx
language: node_js
node_js:
  - "7"
cache:
  directories:
    - "node_modules"
install:
  - npm install
  - bower install
  - bower install ionic-team/ionic-bower#1.3.5
